In [1]:
%pip install numpy

In [2]:
import numpy as np


In [3]:
np.arange(5)
# array([0, 1, 2, 3, 4])


np.zeros((3,2), dtype='int32')
# array([[0, 0], [0, 0], [0, 0]], dtype=int32)

np.zeros((3,2), dtype='int64')
# array([[0, 0], [0, 0], [0, 0]])


np.ones((3,2), dtype='int32')
# array([[1, 1], [1, 1], [1, 1]], dtype=int32)

np.ones((3,2), dtype='int64')
# array([[1, 1], [1, 1], [1, 1]])

array([[1, 1],
       [1, 1],
       [1, 1]])

In [5]:
a = np.arange(6).reshape((3, 2))
a
# reshape 는 길이가 n인 행을 a x b = n 형태의 a 행 b 열을 가지는 2차원 배열의 형태로 만들어줌
# array([[0, 1],
#        [2, 3],
#        [4, 5]])

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
# Q1. 2차원 배열에서 행렬의 각 행 평균을 계산하는 코드를 작성하세요.

# np.mean() == 평균 계산
# 1D array : axis = 0(행) => 1차원 배열(Vector)
# 2D array : axis = 1(열) => 2차원 배열(Matrix)
# 3D array : axis = 2(채널) => 3차원 배열(tensor)
# nD array : n차원(Dimension) 배열 객체

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

arr.shape
# (3, 3)
print(arr)
np.mean((arr), axis=1, dtype="int64")

# -> array([2, 5, 8])

# => 각 행의 평균은 2, 5, 8

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 5, 8])

In [10]:
# Q2. 1차원 배열에서 짝수에 해당하는 인덱스의 값을 출력하는 코드를 작성하세요.

arr = np.array([1,2,3,4,5,6])

even_indexes = np.arange(0, arr.size, 2)
# arr.size 는 배열의 크기를 가져옴

print(arr[even_indexes])
# => [1 3 5]

# ------------------------------------------------

arr[even_indexes]
# => array([1, 3, 5])
# 인덱스는 0부터 시작하기 때문에 1, 3, 5 가 짝수에 해당하는 인덱스

[1 3 5]


array([1, 3, 5])

In [8]:
# Q3. 2차원 배열의 주 대각선 상에 있는 원소들을 출력하는 코드를 작성하세요.
# 주 대각선 : 정방 행렬(square matrix)에서 왼쪽 위에서 오른쪽 아래로 향하는 대각선을 말합니다.
#           이 대각선은 행렬의 행(row)과 열(column)의 인덱스가 동일한 요소들로 구성
# diag(arr) : 주어진 배열의 대각선 요소를 추출하거나, 주어진 배열을 대각 행렬로 변환하는 데 사용
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

arr.shape
# (3, 3)

np.diag(arr)
# => array([1, 5, 9])

array([1, 5, 9])

In [9]:
#Q4. 2차원 배열에서 각 열의 표준편차를 계산하는 코드를 작성하세요
# 표준 편차 : 통계집단의 분산의 정도 또는 자료의 산포도를 나타내는 수치로, 분산의 음이아닌 제곱근, 즉 분산을 제곱근한 것
# std(arr, axis, ..) : 주어진 데이터의 표준 편차(standard deviation)를 계산하는 데 사용
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.std(arr)

# 2.581988897471611

print(arr)
# => [[1 2 3]
# 		[4 5 6]
# 		[7 8 9]]

np.std(arr, axis=0)
# => array([2.44948974, 2.44948974, 2.44948974])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2.44948974, 2.44948974, 2.44948974])

In [11]:
# Q5. 2차원 배열에서 각 행의 최댓값과 그 인덱스를 출력하는 코드를 작성하세요.

# amax(arr, axis, ..) : 배열의 최댓값을 반환, axis = 0 이면 각 열의 최댓값, 1이면 각 행의 최댓값 반환

arr = np.array([[1,2,3], [4,5,6] ,[7,8,9]])

print(arr)
# => [[1 2 3]
# 		[4 5 6]
# 		[7 8 9]]

# 각 행의 최댓값을 구하기

np.amax(arr, axis=1)
# => array([3, 6, 9])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([3, 6, 9])

In [12]:
# Q6. 1차원 배열에서 중앙값(median)을 계산하는 코드를 작성하세요.

# median(arr, axis, ..) : 주어진 배열의 중앙값(median)을 반환
# 중앙값(median) : 데이터를 작은 값에서 큰 값으로 정렬했을 때 가운데에 위치하는 값을 나타냅니다.
#                만약 데이터의 개수가 홀수라면 중앙값은 데이터의 중간에 있는 값이고, 데이터의 개수가 짝수라면 중앙의 두 값의 평균입니다.
arr = np.array([1,2,3,4,5])

np.median(arr)
# => 3.0

3.0

In [13]:
# Q7. 1차원 배열에서 원소의 값이 5 이상인 것들만 출력하는 코드를 작성하세요.

arr = np.array([1,4,6,3,9,2,7,8])

# Boolean Indexing
arr >= 5 # 5보다 크거나 같으면 True | 5보다 작으면 False
# => array([False, False, True, False, True, False, True, True])

arr[arr >= 5] # 5보다 크거나 같은 값만 출력
# => array([6, 9, 7, 8])

array([6, 9, 7, 8])

In [ ]:
# Q8. 1차원 배열에서 원소의 값이 3 또는 5인 것들의 인덱스를 출력하는 코드를 작성하세요.

# where() :NumPy 배열에서 조건에 따라 요소를 선택하는 데 사용됩니다.
#         조건에 따라 요소의 인덱스를 반환하거나, 조건을 만족하는 요소의 값을 다른 값으로 바꾸는 데에도 사용

arr = np.array([1,3,5,2,4,6,3,5,7])

np.where((arr == 3) | (arr == 5))
# => (array([1, 2, 6, 7]),) # 3또는 5인 인덱스는 1,2,6,7번에 위치

# and == &
# or == |

**gaussian_process**

**: 머신러닝에서 많이 사용하는 알고리즘**

[gaussian_process_github](https://github.com/scikit-learn/scikit-learn/blob/9aaed498795f68e5956ea762fef9c440ca9eb239/sklearn/gaussian_process/kernels.py)