## Scikit-Learn 라이브러리



In [1]:
%pip install scikit-learn==1.0.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.5/26.5 MB 38.9 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 0.21.0 requires scikit-learn>=1.2.2, but you have scikit-learn 1.0.2 which is incompatible.


In [2]:
import sklearn
print(sklearn.__version__)

1.0.2


In [3]:
# Classfication - 분류 알고리즘을 사용해서 꽃의 종류 구분해보기
from sklearn.datasets import load_iris
import pandas as pd

In [6]:
iris = load_iris()
iris.data # feature data
iris.target # label data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
# 1. 준비되어있는 데이터셋을 나눈다. (1) 학습용 데이터(train_data) (2) 테스트용 데이터(test_data)
# train_test_split() -> 학습용 데이터 셋과 테스트용 데이터 셋으로 분리하는 역할

from sklearn.model_selection import train_test_split
# X_trian: 학습용 피쳐 데이터, X_test: 테스트용 피쳐 데이터
# y_train: 학습용 레이블 데이터, y_test: 테스트용 레이블 데이터
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=123)


In [16]:
y_test
len(y_train) # 120

120

In [17]:
# 2. 학습을 위한 알고리즘을 불러옵니다.
from sklearn.tree import DecisionTreeClassifier # 분류 알고리즘 (supervised learning)

dt_clf = DecisionTreeClassifier(random_state=123)
dt_clf

DecisionTreeClassifier(random_state=123)

In [18]:
# 3. 학습을 진행합니다. => train_data (X_trian, y_train) > 모의고사

dt_clf.fit(X_train, y_train) # fit() - 학습을 진행

DecisionTreeClassifier(random_state=123)

In [19]:
# 4. 시험을 치러갑니다. test_data(X_test, y_test) > 수능시험
# predict() - 예측하기

predict = dt_clf.predict(X_test)
predict

# => array([1, 2, 2, 1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
#        0, 2, 0, 0, 0, 2, 2, 0])

array([1, 2, 2, 1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 0, 2, 2, 0])

In [21]:
# 5. 채점을 진행합니다.
# accuracy_score()

from sklearn.metrics import accuracy_score

accuracy_score(y_test, predict) # 정답(t_test)과 실제 알고리즘(predict)이 풀이 한 정답이 일치한지 확인
# 정확도 출력

# => 0.9666666666666667

0.9666666666666667

In [ ]:
df = pd.DataFrame(data=X_test, columns=iris.feature_names)
# 수능문제지 (X_test) | aris.data 는 범위가 너무 큼

df["answer"] = y_test
df["predict"] = predict

df

## 교차검증
1. K Fold 검증
2. Stratified 검증
3. cross_val_score() : 검증을 쉽게 할 수 있도록 도와주는 함수

In [27]:
# (1) K Fold
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# 데이터 로드
iris = load_iris()
train_data = iris.data
train_target = iris.target

# 모델 학습 및 평가 함수 정의
def train_and_evaluate(train_index, test_index, model, train_data, train_target):
    # 학습 및 검증 데이터 분리
    X_train, X_test = train_data[train_index], train_data[test_index]
    y_train, y_test = train_target[train_index], train_target[test_index]

    # 모델 학습 및 예측
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    # 정확도 계산
    accuracy = accuracy_score(y_test, predictions)
    return accuracy, X_train.shape[0], X_test.shape[0], test_index

# K-Fold 교차 검증 설정
kfold = KFold(n_splits=5)
cv_accuracy = []
dt_clf = DecisionTreeClassifier()

# K-Fold 교차 검증 수행
for fold, (train_index, test_index) in enumerate(kfold.split(train_data), 1):
    accuracy, train_size, test_size, test_idx = train_and_evaluate(
        train_index, test_index, dt_clf, train_data, train_target
    )
    cv_accuracy.append(accuracy)

    print(f"{fold}번째 트레이닝")
    print(f"검증 정확도 : {accuracy}, 학습 데이터 크기: {train_size}, 검증 데이터 크기: {test_size}")
    print(f"검증 데이터 셋 인덱스 값: {test_idx}")
    print(f"==="* 10)

# 최종 정확도 평균 출력
print("최종 정확도 평균 값: ", np.mean(cv_accuracy))

1번째 트레이닝
검증 정확도 : 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
검증 데이터 셋 인덱스 값: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
2번째 트레이닝
검증 정확도 : 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
검증 데이터 셋 인덱스 값: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
3번째 트레이닝
검증 정확도 : 0.8666666666666667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
검증 데이터 셋 인덱스 값: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
4번째 트레이닝
검증 정확도 : 0.9333333333333333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
검증 데이터 셋 인덱스 값: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
5번째 트레이닝
검증 정확도 : 0.8, 학습 데이터 크기: 120, 검증 데이터 크기: 30
검증 데이터 셋 인덱스 값: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
최종 정확도 평균 값:  0.9199999999999999


In [28]:
# (2) Stratified KFold
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# 데이터 로드
iris = load_iris()
features = iris.data
label = iris.target

# 모델 초기화
dt_clf = DecisionTreeClassifier(random_state=156)

# 모델 학습 및 평가 함수 정의
def train_and_evaluate(train_index, test_index, model, features, label):
    # 학습 및 검증 데이터 분리
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    # 모델 학습 및 예측
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    # 정확도 계산
    accuracy = np.round(accuracy_score(y_test, predictions), 4)
    return accuracy, X_train.shape[0], X_test.shape[0], test_index

# K-Fold 교차 검증 설정
skfold = StratifiedKFold(n_splits=3)
cv_accuracy = []

# K-Fold 교차 검증 수행
for fold, (train_index, test_index) in enumerate(skfold.split(features, label), 1):
    accuracy, train_size, test_size, test_idx = train_and_evaluate(
        train_index, test_index, dt_clf, features, label
    )
    cv_accuracy.append(accuracy)

    print(f"{fold}번째 트레이닝")
    print(f"검증 정확도 : {accuracy}, 학습 데이터 크기: {train_size}, 검증 데이터 크기: {test_size}")
    print(f"검증 데이터 셋 인덱스 값: {test_idx}")
    print(f"==="* 10)

# 최종 정확도 평균 출력
print("\n최종 정확도 평균 값: ", np.mean(cv_accuracy))

1번째 트레이닝
검증 정확도 : 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
검증 데이터 셋 인덱스 값: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
2번째 트레이닝
검증 정확도 : 0.94, 학습 데이터 크기: 100, 검증 데이터 크기: 50
검증 데이터 셋 인덱스 값: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
3번째 트레이닝
검증 정확도 : 0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
검증 데이터 셋 인덱스 값: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

최종 정확도 평균 값:  0.9666666666666667


In [30]:
# (3) cross_val_score()
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data # x
label = iris_data.target # y

scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=4)
# scoring : 평가지표, cv : 교차 검증 폴드의 수
print('교차 검증별 정확도: ', np.round(scores, 4))
print('평균 검증 정확도: ', np.round(np.mean(scores), 4))


교차 검증별 정확도:  [0.9737 0.9474 0.9459 0.973 ]
평균 검증 정확도:  0.96


## 데이터 인코딩
1. Label Encoding
2. OneHot Encoding
3. GetDummies : Pandas의 df를 활용한 방법

In [31]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder

items = ["강남구", "서초구", "송파구", "노원구", "마포구", "마포구", "용산구", "용산구"]

# LabelEncoder를 객체로 생성한 후 , fit()과 transfrom()으로 label 인코딩을 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print("인코딩 변환값 : ", labels) # 문자열 값 -> 숫자형 값으로 변경 (Label Encoding)

인코딩 변환값 :  [0 3 4 1 2 2 5 5]


In [38]:
# OneHot Encoding
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ["강남구", "서초구", "송파구", "노원구", "마포구", "마포구", "용산구", "용산구"]

# 2차원 ndarray로 변환한다.
# reshape() 함수의 첫 번째 인자로 -1을 주면 해당 차원의 크기를 자동으로 계산하여 맞춰준다.
# 두 번째 인자로 1을 주면 열의 크기를 1로 지정하여 결과적으로 1개의 열로 이루어진 2차원 배열을 생성한다.
# 이렇게 2차원 배열로 변환된 데이터는 머신 러닝 모델에 입력으로 사용하기에 적합한 형태가 된다.
# 머신 러닝 모델은 입력으로 2차원 배열을 기대하므로, 데이터를 이와 같은 형태로 변환하여 모델에 사용해야 한다.

items = np.array(items).reshape(-1,1)

# 원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

# OneHotEncoder로 변환한 결과는 최소행렬(Sparse Matrix)이므로 toarray()를 이용하여 밀집 행렬(Dense Matrix)로 변환한다.
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)


원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]
원-핫 인코딩 데이터 변환
(8, 6)


In [40]:
# df.get_dummies() : 원-핫 인코딩을 쉽게하는 방법
import pandas as pd

df = pd.DataFrame({"item": ["강남구", "서초구", "송파구", "노원구", "마포구", "마포구", "용산구", "용산구"]})

pd.get_dummies(df)


item_강남구  item_노원구  item_마포구  item_서초구  item_송파구  item_용산구
0         1         0         0         0         0         0
1         0         0         0         1         0         0
2         0         0         0         0         1         0
3         0         1         0         0         0         0
4         0         0         1         0         0         0
5         0         0         1         0         0         0
6         0         0         0         0         0         1
7         0         0         0         0         0         1

In [43]:
import pandas as pd

data = {'fruit' : ['apple', 'banana', 'cherry', 'apple', 'cherry'],
        'color' : ['red', 'yellow', 'red', 'green', 'red']}

df = pd.DataFrame(data)
pd.get_dummies(df)

fruit_apple  fruit_banana  fruit_cherry  color_green  color_red  \
0            1             0             0            0          1   
1            0             1             0            0          0   
2            0             0             1            0          1   
3            1             0             0            1          0   
4            0             0             1            0          1   

   color_yellow  
0             0  
1             1  
2             0  
3             0  
4             0